// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptAnyReducer from "../accept_any_reducer";
import AddMemoryReducer from "../add_memory_reducer";
import AdminSendReducer from "../admin_send_reducer";
import AdvanceBuildJobReducer from "../advance_build_job_reducer";
import AdvanceScenarioReducer from "../advance_scenario_reducer";
import AssignJobReducer from "../assign_job_reducer";
import BeginActionReducer from "../begin_action_reducer";
import BuilderSayReducer from "../builder_say_reducer";
import ClaimBuildJobReducer from "../claim_build_job_reducer";
import ClearAdminSessionReducer from "../clear_admin_session_reducer";
import ConfirmActionReducer from "../confirm_action_reducer";
import ConsumeDirectiveReducer from "../consume_directive_reducer";
import ConsumeInventoryReducer from "../consume_inventory_reducer";
import DeclineQuestReducer from "../decline_quest_reducer";
import DirectorReplyReducer from "../director_reply_reducer";
import EndScenarioReducer from "../end_scenario_reducer";
import EnqueueBuildReducer from "../enqueue_build_reducer";
import FinishActionReducer from "../finish_action_reducer";
import JoinPartyReducer from "../join_party_reducer";
import MarkPlayerMessageRespondedReducer from "../mark_player_message_responded_reducer";
import PlayerSayToBuilderReducer from "../player_say_to_builder_reducer";
import PostChatReducer from "../post_chat_reducer";
import ProposeActionReducer from "../propose_action_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import RejectActionReducer from "../reject_action_reducer";
import RemoveBuilderReducer from "../remove_builder_reducer";
import RequestRecruitmentReducer from "../request_recruitment_reducer";
import SetAdvancementReducer from "../set_advancement_reducer";
import SetBuilderPersonalityReducer from "../set_builder_personality_reducer";
import SetBuilderStateReducer from "../set_builder_state_reducer";
import SetInventoryReducer from "../set_inventory_reducer";
import SetPlayerOfflineReducer from "../set_player_offline_reducer";
import SetWorldClockReducer from "../set_world_clock_reducer";
import StartScenarioReducer from "../start_scenario_reducer";
import SubmitThinkResultReducer from "../submit_think_result_reducer";
import UpdateBuilderPosReducer from "../update_builder_pos_reducer";
import UpdatePlayerPosReducer from "../update_player_pos_reducer";
import UpsertBuilderReducer from "../upsert_builder_reducer";

export type AcceptAnyParams = __Infer<typeof AcceptAnyReducer>;
export type AddMemoryParams = __Infer<typeof AddMemoryReducer>;
export type AdminSendParams = __Infer<typeof AdminSendReducer>;
export type AdvanceBuildJobParams = __Infer<typeof AdvanceBuildJobReducer>;
export type AdvanceScenarioParams = __Infer<typeof AdvanceScenarioReducer>;
export type AssignJobParams = __Infer<typeof AssignJobReducer>;
export type BeginActionParams = __Infer<typeof BeginActionReducer>;
export type BuilderSayParams = __Infer<typeof BuilderSayReducer>;
export type ClaimBuildJobParams = __Infer<typeof ClaimBuildJobReducer>;
export type ClearAdminSessionParams = __Infer<typeof ClearAdminSessionReducer>;
export type ConfirmActionParams = __Infer<typeof ConfirmActionReducer>;
export type ConsumeDirectiveParams = __Infer<typeof ConsumeDirectiveReducer>;
export type ConsumeInventoryParams = __Infer<typeof ConsumeInventoryReducer>;
export type DeclineQuestParams = __Infer<typeof DeclineQuestReducer>;
export type DirectorReplyParams = __Infer<typeof DirectorReplyReducer>;
export type EndScenarioParams = __Infer<typeof EndScenarioReducer>;
export type EnqueueBuildParams = __Infer<typeof EnqueueBuildReducer>;
export type FinishActionParams = __Infer<typeof FinishActionReducer>;
export type JoinPartyParams = __Infer<typeof JoinPartyReducer>;
export type MarkPlayerMessageRespondedParams = __Infer<typeof MarkPlayerMessageRespondedReducer>;
export type PlayerSayToBuilderParams = __Infer<typeof PlayerSayToBuilderReducer>;
export type PostChatParams = __Infer<typeof PostChatReducer>;
export type ProposeActionParams = __Infer<typeof ProposeActionReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type RejectActionParams = __Infer<typeof RejectActionReducer>;
export type RemoveBuilderParams = __Infer<typeof RemoveBuilderReducer>;
export type RequestRecruitmentParams = __Infer<typeof RequestRecruitmentReducer>;
export type SetAdvancementParams = __Infer<typeof SetAdvancementReducer>;
export type SetBuilderPersonalityParams = __Infer<typeof SetBuilderPersonalityReducer>;
export type SetBuilderStateParams = __Infer<typeof SetBuilderStateReducer>;
export type SetInventoryParams = __Infer<typeof SetInventoryReducer>;
export type SetPlayerOfflineParams = __Infer<typeof SetPlayerOfflineReducer>;
export type SetWorldClockParams = __Infer<typeof SetWorldClockReducer>;
export type StartScenarioParams = __Infer<typeof StartScenarioReducer>;
export type SubmitThinkResultParams = __Infer<typeof SubmitThinkResultReducer>;
export type UpdateBuilderPosParams = __Infer<typeof UpdateBuilderPosReducer>;
export type UpdatePlayerPosParams = __Infer<typeof UpdatePlayerPosReducer>;
export type UpsertBuilderParams = __Infer<typeof UpsertBuilderReducer>;

