// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddMemoryReducer from "../add_memory_reducer";
import BuilderSayReducer from "../builder_say_reducer";
import ConsumeDirectiveReducer from "../consume_directive_reducer";
import DeclineQuestReducer from "../decline_quest_reducer";
import JoinPartyReducer from "../join_party_reducer";
import PostChatReducer from "../post_chat_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import RemoveBuilderReducer from "../remove_builder_reducer";
import RequestRecruitmentReducer from "../request_recruitment_reducer";
import SetAdvancementReducer from "../set_advancement_reducer";
import SetPlayerOfflineReducer from "../set_player_offline_reducer";
import SetWorldClockReducer from "../set_world_clock_reducer";
import SubmitThinkResultReducer from "../submit_think_result_reducer";
import UpdateBuilderPosReducer from "../update_builder_pos_reducer";
import UpdatePlayerPosReducer from "../update_player_pos_reducer";
import UpsertBuilderReducer from "../upsert_builder_reducer";

export type AddMemoryParams = __Infer<typeof AddMemoryReducer>;
export type BuilderSayParams = __Infer<typeof BuilderSayReducer>;
export type ConsumeDirectiveParams = __Infer<typeof ConsumeDirectiveReducer>;
export type DeclineQuestParams = __Infer<typeof DeclineQuestReducer>;
export type JoinPartyParams = __Infer<typeof JoinPartyReducer>;
export type PostChatParams = __Infer<typeof PostChatReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type RemoveBuilderParams = __Infer<typeof RemoveBuilderReducer>;
export type RequestRecruitmentParams = __Infer<typeof RequestRecruitmentReducer>;
export type SetAdvancementParams = __Infer<typeof SetAdvancementReducer>;
export type SetPlayerOfflineParams = __Infer<typeof SetPlayerOfflineReducer>;
export type SetWorldClockParams = __Infer<typeof SetWorldClockReducer>;
export type SubmitThinkResultParams = __Infer<typeof SubmitThinkResultReducer>;
export type UpdateBuilderPosParams = __Infer<typeof UpdateBuilderPosReducer>;
export type UpdatePlayerPosParams = __Infer<typeof UpdatePlayerPosReducer>;
export type UpsertBuilderParams = __Infer<typeof UpsertBuilderReducer>;

