// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  kind: __t.string(),
  summary: __t.string(),
  paramsJson: __t.string().name("params_json"),
  areaX: __t.f64().name("area_x"),
  areaY: __t.f64().name("area_y"),
  areaZ: __t.f64().name("area_z"),
  radius: __t.f64(),
  world: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  decidedAt: __t.timestamp().name("decided_at"),
});
