// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.i32().primaryKey().name("npc_id"),
  name: __t.string(),
  persona: __t.string(),
  town: __t.string(),
  schedule: __t.string(),
  thought: __t.string(),
  partyId: __t.u64().name("party_id"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  world: __t.string(),
  job: __t.string(),
  homeX: __t.f64().name("home_x"),
  homeY: __t.f64().name("home_y"),
  homeZ: __t.f64().name("home_z"),
  homeWorld: __t.string().name("home_world"),
  state: __t.string(),
  heldItem: __t.string().name("held_item"),
  personality: __t.string(),
  backstory: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
