// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Builder = __t.object("Builder", {
  npcId: __t.i32(),
  name: __t.string(),
  persona: __t.string(),
  town: __t.string(),
  schedule: __t.string(),
  thought: __t.string(),
  partyId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  world: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Builder = __Infer<typeof Builder>;

export const BuilderMemory = __t.object("BuilderMemory", {
  id: __t.u64(),
  builderId: __t.i32(),
  kind: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type BuilderMemory = __Infer<typeof BuilderMemory>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  builderId: __t.i32(),
  speaker: __t.string(),
  text: __t.string(),
  audience: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  playerUuid: __t.string(),
  builderId: __t.i32(),
  questId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const Player = __t.object("Player", {
  uuid: __t.string(),
  name: __t.string(),
  online: __t.bool(),
  difficulty: __t.string(),
  partyId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  world: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAdvancement = __t.object("PlayerAdvancement", {
  key: __t.string(),
  playerUuid: __t.string(),
  advancementId: __t.string(),
  done: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerAdvancement = __Infer<typeof PlayerAdvancement>;

export const Quest = __t.object("Quest", {
  id: __t.u64(),
  playerUuid: __t.string(),
  builderId: __t.i32(),
  advancementId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  tier: __t.i32(),
  state: __t.string(),
  createdAt: __t.timestamp(),
});
export type Quest = __Infer<typeof Quest>;

export const RecruitBudget = __t.object("RecruitBudget", {
  playerUuid: __t.string(),
  phaseId: __t.i64(),
  used: __t.i32(),
});
export type RecruitBudget = __Infer<typeof RecruitBudget>;

export const StoryDirective = __t.object("StoryDirective", {
  id: __t.u64(),
  kind: __t.string(),
  builderId: __t.i32(),
  playerUuid: __t.string(),
  text: __t.string(),
  questId: __t.u64(),
  consumed: __t.bool(),
  createdAt: __t.timestamp(),
});
export type StoryDirective = __Infer<typeof StoryDirective>;

export const WorldClock = __t.object("WorldClock", {
  id: __t.i32(),
  timeOfDay: __t.i64(),
  fullTime: __t.i64(),
  phase: __t.string(),
  phaseId: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type WorldClock = __Infer<typeof WorldClock>;

