// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  builderId: __t.i32().name("builder_id"),
  kind: __t.string(),
  siteX: __t.f64().name("site_x"),
  siteY: __t.f64().name("site_y"),
  siteZ: __t.f64().name("site_z"),
  world: __t.string(),
  step: __t.u32(),
  total: __t.u32(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
