// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  kind: __t.string(),
  summary: __t.string(),
  paramsJson: __t.string(),
  areaX: __t.f64(),
  areaY: __t.f64(),
  areaZ: __t.f64(),
  radius: __t.f64(),
  world: __t.string(),
};
