// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.string(),
  status: __t.string(),
  areaX: __t.f64().name("area_x"),
  areaY: __t.f64().name("area_y"),
  areaZ: __t.f64().name("area_z"),
  radius: __t.f64(),
  world: __t.string(),
  intensity: __t.i32(),
  wave: __t.u32(),
  totalWaves: __t.u32().name("total_waves"),
  endsFullTime: __t.i64().name("ends_full_time"),
  paramsJson: __t.string().name("params_json"),
  startedAt: __t.timestamp().name("started_at"),
});
