// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  timeOfDay: __t.i64().name("time_of_day"),
  fullTime: __t.i64().name("full_time"),
  phase: __t.string(),
  phaseId: __t.i64().name("phase_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
